name: Creating logger
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Run tests
      run: python -m unittest discover ${{ github.workspace }} -s tests